/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2018-05-01 09:46:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;

public final class ClassSchedule_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        <html>\r\n");
      out.write("\r\n");
      out.write("        <head>\r\n");
      out.write("            <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("            <title>课程表</title>\r\n");
      out.write("            <LINK href=\"./lib/easyui.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("            <LINK href=\"./lib/icon.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("            <LINK href=\"./lib/demo.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("            <SCRIPT src=\"./lib/jquery-1.11.3.min.js\" type=\"text/javascript\"></SCRIPT>\r\n");
      out.write("            <SCRIPT src=\"./lib/jquery.easyui.min.js\" type=\"text/javascript\"></SCRIPT>\r\n");
      out.write("            <script>\r\n");
      out.write("                window.onload = function() {\r\n");
      out.write("                    if (sessionStorage.id == null) {\r\n");
      out.write("                        window.location.href = \"http://localhost:5716/SigningSystemServer/Login.jsp\";\r\n");
      out.write("                    }\r\n");
      out.write("                    GetSchedule();\r\n");
      out.write("                    ChangeColor();\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                function GetSchedule() {\r\n");
      out.write("                    var classname = document.getElementById(\"classname\").innerText;\r\n");
      out.write("                    jQuery.ajax({\r\n");
      out.write("                        url: \"");
      out.print(request.getContextPath());
      out.write("/GetCrouseServlet\", //这里是传入的 servlet  \r\n");
      out.write("                        type: \"post\",\r\n");
      out.write("                        data: {\r\n");
      out.write("                            id: sessionStorage.id,\r\n");
      out.write("                            classname: classname,\r\n");
      out.write("                        }, //这里是传进去的参数  \r\n");
      out.write("                        dataType: \"json\",\r\n");
      out.write("                        success: function(data) {\r\n");
      out.write("                            ShowSchedule(data);\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                function ShowSchedule(data) {\r\n");
      out.write("                    console.log(data);\r\n");
      out.write("                    var scheduleInfo = eval(data.scheduleInfo);\r\n");
      out.write("                    if (scheduleInfo != undefined) {\r\n");
      out.write("                        console.log(\"scheduleInfo.length info:\" + scheduleInfo.length);\r\n");
      out.write("                        var crouse = document.getElementsByClassName(\"crouse\");\r\n");
      out.write("                        for (var i in scheduleInfo) {\r\n");
      out.write("                            var crouseInfo = scheduleInfo[i];\r\n");
      out.write("                            var day = crouseInfo.day;\r\n");
      out.write("                            var cindex = crouseInfo.cindex;\r\n");
      out.write("                            var cname = crouseInfo.cname;\r\n");
      out.write("                            console.log(crouseInfo.day + crouseInfo.cname);\r\n");
      out.write("                            crouse[5 * (cindex - 1) + (day - 1)].textContent = cname;\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                function ChangeColor() {\r\n");
      out.write("\r\n");
      out.write("                    var color = new Array();\r\n");
      out.write("                    var bcolor = new Array();\r\n");
      out.write("                    for (i = 0; i < $(\".crouse\").length; i++) {\r\n");
      out.write("                        color[i] = \"#\" + Math.floor(Math.random() * 0xffffff).toString(16);\r\n");
      out.write("                        bcolor[i] = \"#\" + Math.floor(Math.random() * 0xffffff).toString(16);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    $(\".crouse\").each(function() {\r\n");
      out.write("\r\n");
      out.write("                        switch ($(this).text()) {\r\n");
      out.write("                            case \"高等数学\":\r\n");
      out.write("                                {\r\n");
      out.write("                                    $(this).css({\r\n");
      out.write("                                        \"color\": color[0],\r\n");
      out.write("                                        \"background\": bcolor[0]\r\n");
      out.write("                                    });\r\n");
      out.write("                                    break;\r\n");
      out.write("                                }\r\n");
      out.write("                            case \"线性代数\":\r\n");
      out.write("                                {\r\n");
      out.write("                                    $(this).css({\r\n");
      out.write("                                        \"color\": color[1],\r\n");
      out.write("                                        \"background\": bcolor[1]\r\n");
      out.write("                                    });\r\n");
      out.write("                                    break;\r\n");
      out.write("                                }\r\n");
      out.write("                            case \"概率论与数理统计\":\r\n");
      out.write("                                {\r\n");
      out.write("                                    $(this).css({\r\n");
      out.write("                                        \"color\": color[2],\r\n");
      out.write("                                        \"background\": bcolor[2]\r\n");
      out.write("                                    });\r\n");
      out.write("                                    break;\r\n");
      out.write("                                }\r\n");
      out.write("                            case \"政治\":\r\n");
      out.write("                                {\r\n");
      out.write("                                    $(this).css({\r\n");
      out.write("                                        \"color\": color[3],\r\n");
      out.write("                                        \"background\": bcolor[3]\r\n");
      out.write("                                    });\r\n");
      out.write("                                    break;\r\n");
      out.write("                                }\r\n");
      out.write("                            case \"数据结构\":\r\n");
      out.write("                                {\r\n");
      out.write("                                    $(this).css({\r\n");
      out.write("                                        \"color\": color[4],\r\n");
      out.write("                                        \"background\": bcolor[4]\r\n");
      out.write("                                    });\r\n");
      out.write("                                    break;\r\n");
      out.write("                                }\r\n");
      out.write("                            case \"操作系统\":\r\n");
      out.write("                                {\r\n");
      out.write("                                    $(this).css({\r\n");
      out.write("                                        \"color\": color[5],\r\n");
      out.write("                                        \"background\": bcolor[5]\r\n");
      out.write("                                    });\r\n");
      out.write("                                    break;\r\n");
      out.write("                                }\r\n");
      out.write("                            case \"计算机组成原理\":\r\n");
      out.write("                                {\r\n");
      out.write("                                    $(this).css({\r\n");
      out.write("                                        \"color\": color[6],\r\n");
      out.write("                                        \"background\": bcolor[6]\r\n");
      out.write("                                    });\r\n");
      out.write("                                    break;\r\n");
      out.write("                                }\r\n");
      out.write("                            case \"计算机网络\":\r\n");
      out.write("                                {\r\n");
      out.write("                                    $(this).css({\r\n");
      out.write("                                        \"color\": color[7],\r\n");
      out.write("                                        \"background\": bcolor[7]\r\n");
      out.write("                                    });\r\n");
      out.write("                                    break;\r\n");
      out.write("                                }\r\n");
      out.write("                            case \"微机原理\":\r\n");
      out.write("                                {\r\n");
      out.write("                                    $(this).css({\r\n");
      out.write("                                        \"color\": color[8],\r\n");
      out.write("                                        \"background\": bcolor[8]\r\n");
      out.write("                                    });\r\n");
      out.write("                                    break;\r\n");
      out.write("                                }\r\n");
      out.write("                            case \"C语言\":\r\n");
      out.write("                                {\r\n");
      out.write("                                    $(this).css({\r\n");
      out.write("                                        \"color\": color[9],\r\n");
      out.write("                                        \"background\": bcolor[9]\r\n");
      out.write("                                    });\r\n");
      out.write("                                    break;\r\n");
      out.write("                                }\r\n");
      out.write("                            case \"Java\":\r\n");
      out.write("                                {\r\n");
      out.write("                                    $(this).css({\r\n");
      out.write("                                        \"color\": color[10],\r\n");
      out.write("                                        \"background\": bcolor[10]\r\n");
      out.write("                                    });\r\n");
      out.write("                                    break;\r\n");
      out.write("                                }\r\n");
      out.write("                            case \"Python\":\r\n");
      out.write("                                {\r\n");
      out.write("                                    $(this).css({\r\n");
      out.write("                                        \"color\": color[11],\r\n");
      out.write("                                        \"background\": bcolor[11]\r\n");
      out.write("                                    });\r\n");
      out.write("                                    break;\r\n");
      out.write("                                }\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("                }\r\n");
      out.write("            </script>\r\n");
      out.write("        </head>\r\n");
      out.write("\r\n");
      out.write("        <body>\r\n");
      out.write("            <STYLE type=\"text/css\">\r\n");
      out.write("                .left {\r\n");
      out.write("                    width: 120px;\r\n");
      out.write("                    float: left;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                .left table {\r\n");
      out.write("                    background: #E0ECFF;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                .left td {\r\n");
      out.write("                    background: #eee;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                .right {\r\n");
      out.write("                    float: right;\r\n");
      out.write("                    width: 570px;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                .right table {\r\n");
      out.write("                    background: #E0ECFF;\r\n");
      out.write("                    width: 100%;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                .right td {\r\n");
      out.write("                    background: #fafafa;\r\n");
      out.write("                    color: #444;\r\n");
      out.write("                    text-align: center;\r\n");
      out.write("                    padding: 2px;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                .right td {\r\n");
      out.write("                    background: #E0ECFF;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                .right td.drop {\r\n");
      out.write("                    background: #fafafa;\r\n");
      out.write("                    width: 100px;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                .right td.over {\r\n");
      out.write("                    background: #FBEC88;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                .item {\r\n");
      out.write("                    text-align: center;\r\n");
      out.write("                    border: 1px solid #499B33;\r\n");
      out.write("                    background: #fafafa;\r\n");
      out.write("                    color: #444;\r\n");
      out.write("                    width: 100px;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                .assigned {\r\n");
      out.write("                    border: 1px solid #BC2A4D;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                .trash {\r\n");
      out.write("                    background-color: red;\r\n");
      out.write("                }\r\n");
      out.write("            </STYLE>\r\n");
      out.write("\r\n");
      out.write("            <div style=\"width:700px;\">\r\n");
      out.write("                <DIV style=\"width:700px;float:left;\">\r\n");
      out.write("                    <DIV class=\"left\">\r\n");
      out.write("                        <TABLE>\r\n");
      out.write("                            <TBODY>\r\n");
      out.write("                                <TR>\r\n");
      out.write("                                    <TD>\r\n");
      out.write("                                        <DIV class=\"item\">高等数学</DIV>\r\n");
      out.write("                                    </TD>\r\n");
      out.write("                                </TR>\r\n");
      out.write("                                <TR>\r\n");
      out.write("                                    <TD>\r\n");
      out.write("                                        <DIV class=\"item\">线性代数</DIV>\r\n");
      out.write("                                    </TD>\r\n");
      out.write("                                </TR>\r\n");
      out.write("                                <TR>\r\n");
      out.write("                                    <TD>\r\n");
      out.write("                                        <DIV class=\"item\">概率论与数理统计</DIV>\r\n");
      out.write("                                    </TD>\r\n");
      out.write("                                </TR>\r\n");
      out.write("                                <TR>\r\n");
      out.write("                                    <TD>\r\n");
      out.write("                                        <DIV class=\"item\">政治</DIV>\r\n");
      out.write("                                    </TD>\r\n");
      out.write("                                </TR>\r\n");
      out.write("                                <TR>\r\n");
      out.write("                                    <TD>\r\n");
      out.write("                                        <DIV class=\"item\">数据结构</DIV>\r\n");
      out.write("                                    </TD>\r\n");
      out.write("                                </TR>\r\n");
      out.write("                                <TR>\r\n");
      out.write("                                    <TD>\r\n");
      out.write("                                        <DIV class=\"item\">操作系统</DIV>\r\n");
      out.write("                                    </TD>\r\n");
      out.write("                                </TR>\r\n");
      out.write("                                <TR>\r\n");
      out.write("                                    <TD>\r\n");
      out.write("                                        <DIV class=\"item\">计算机组成原理</DIV>\r\n");
      out.write("                                    </TD>\r\n");
      out.write("                                </TR>\r\n");
      out.write("                                <TR>\r\n");
      out.write("                                    <TD>\r\n");
      out.write("                                        <DIV class=\"item\">计算机网络</DIV>\r\n");
      out.write("                                    </TD>\r\n");
      out.write("                                </TR>\r\n");
      out.write("                                <TR>\r\n");
      out.write("                                    <TD>\r\n");
      out.write("                                        <DIV class=\"item\">微机原理</DIV>\r\n");
      out.write("                                    </TD>\r\n");
      out.write("                                </TR>\r\n");
      out.write("                                <TR>\r\n");
      out.write("                                    <TD>\r\n");
      out.write("                                        <DIV class=\"item\">C语言</DIV>\r\n");
      out.write("                                    </TD>\r\n");
      out.write("                                </TR>\r\n");
      out.write("                                <TR>\r\n");
      out.write("                                    <TD>\r\n");
      out.write("                                        <DIV class=\"item\">Java</DIV>\r\n");
      out.write("                                    </TD>\r\n");
      out.write("                                </TR>\r\n");
      out.write("                                <TR>\r\n");
      out.write("                                    <TD>\r\n");
      out.write("                                        <DIV class=\"item\">Python</DIV>\r\n");
      out.write("                                    </TD>\r\n");
      out.write("                                </TR>\r\n");
      out.write("                            </TBODY>\r\n");
      out.write("                        </TABLE>\r\n");
      out.write("                    </DIV>\r\n");
      out.write("                    <DIV class=\"right\">\r\n");
      out.write("                        <table border=\"1\">\r\n");
      out.write("                            <TBODY>\r\n");
      out.write("                                <caption id=\"classname\">物联网工程课程表</caption>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td colspan=2 class=\"blank\">&nbsp;</td>\r\n");
      out.write("                                    <td class=\"title\">星期一</td>\r\n");
      out.write("                                    <td class=\"title\">星期二</td>\r\n");
      out.write("                                    <td class=\"title\">星期三</td>\r\n");
      out.write("                                    <td class=\"title\">星期四</td>\r\n");
      out.write("                                    <td class=\"title\">星期五</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td rowspan=5 class=\"time\">上午</td>\r\n");
      out.write("                                    <td class=\"cindex\">1</td>\r\n");
      out.write("\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"cindex\">2</td>\r\n");
      out.write("\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td colspan=6 align=\"center\">课间操</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"cindex\">3</td>\r\n");
      out.write("\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"cindex\">4</td>\r\n");
      out.write("\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td colspan=7 align=\"center\">午间休息</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td rowspan=4 class=\"time\">下午</td>\r\n");
      out.write("                                    <td class=\"cindex\">5</td>\r\n");
      out.write("\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"cindex\">6</td>\r\n");
      out.write("\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"cindex\">7</td>\r\n");
      out.write("\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"cindex\">8</td>\r\n");
      out.write("\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td colspan=7 align=\"center\">晚间休息</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td rowspan=2 class=\"time\">晚上</td>\r\n");
      out.write("                                    <td class=\"cindex\">9</td>\r\n");
      out.write("\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"cindex\">10</td>\r\n");
      out.write("\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("                                    <td class=\"crouse drop\"></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </TBODY>\r\n");
      out.write("                        </table>\r\n");
      out.write("\r\n");
      out.write("                    </DIV>\r\n");
      out.write("\r\n");
      out.write("                </DIV>\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("                    <button style=\"width:200px\" onclick=\"SaveCrouse()\">保存课程表</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <hr size=\"1\" width=\"20%\" color=\"black\" noshade=\"noshade\" align=\"left\" />\r\n");
      out.write("                <div>\r\n");
      out.write("                    <input id=\"Days\" list=\"day\" />\r\n");
      out.write("                    <datalist id=\"day\">\r\n");
      out.write("                <option value=\"星期1\"></option>\r\n");
      out.write("                <option value=\"星期2\"></option>\r\n");
      out.write("                <option value=\"星期3\"></option>\r\n");
      out.write("                <option value=\"星期4\"></option>\r\n");
      out.write("                <option value=\"星期5\"></option>\r\n");
      out.write("            </datalist>\r\n");
      out.write("\r\n");
      out.write("                    <input id=\"Crouses\" list=\"crouse\" />\r\n");
      out.write("                    <datalist id=\"crouse\">\r\n");
      out.write("                <option value=\"第1节\"></option>\r\n");
      out.write("                <option value=\"第2节\"></option>\r\n");
      out.write("                <option value=\"第3节\"></option>\r\n");
      out.write("                <option value=\"第4节\"></option>\r\n");
      out.write("                <option value=\"第5节\"></option>\r\n");
      out.write("                <option value=\"第6节\"></option>\r\n");
      out.write("            </datalist>\r\n");
      out.write("                    <button onclick=\"GetCrouse()\">Search</button>\r\n");
      out.write("                    <div id=\"res\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <hr size=\"1\" width=\"20%\" color=\"black\" noshade=\"noshade\" align=\"left\" />\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <input type=\"button\" onclick=\"ChangeColor()\" value=\"Change color of table\">\r\n");
      out.write("                </tr>\r\n");
      out.write("        </body>\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("            function GetCrouse() {\r\n");
      out.write("                var crou = String(document.getElementById('Crouses').value);\r\n");
      out.write("                var da = String(document.getElementById('Days').value);\r\n");
      out.write("                var w = parseInt(da.substr(da.indexOf(\"期\") + 1, 1));\r\n");
      out.write("                var n = parseInt(crou.substr(crou.indexOf(\"第\") + 1, 1));\r\n");
      out.write("                var result = document.getElementsByClassName(\"crouse\")[5 * (n - 1) + (w - 1)].textContent;\r\n");
      out.write("                document.getElementById(\"res\").innerHTML = \"课程：\" + result;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function SaveCrouse() {\r\n");
      out.write("                if ($('.crouse .item').length == 0) {\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("                var crouse = {};\r\n");
      out.write("                var classname = document.getElementById(\"classname\").innerText;\r\n");
      out.write("                $('.crouse .item').each(function() {\r\n");
      out.write("                    var t = $(this).parent().parent().children(\".cindex\");\r\n");
      out.write("                    var day = $(this).parent().index() - t.index();\r\n");
      out.write("                    var cindex = t.text();\r\n");
      out.write("                    var cname = $(this).text();\r\n");
      out.write("                    var crou = day + \" \" + cindex;\r\n");
      out.write("                    crouse[crou] = cname;\r\n");
      out.write("                });\r\n");
      out.write("                var crousejson = JSON.stringify(crouse);\r\n");
      out.write("                jQuery.ajax({\r\n");
      out.write("                    url: \"");
      out.print(request.getContextPath());
      out.write("/SaveCrouseServlet\", //这里是传入的 servlet  \r\n");
      out.write("                    type: \"post\",\r\n");
      out.write("                    data: {\r\n");
      out.write("                        id: sessionStorage.id,\r\n");
      out.write("                        classname: classname,\r\n");
      out.write("                        crouse: crousejson\r\n");
      out.write("                    }, //这里是传进去的参数  \r\n");
      out.write("                    dataType: \"text\",\r\n");
      out.write("                    success: function(data) {\r\n");
      out.write("                        if (data == \"SUCCEEDED\")\r\n");
      out.write("                            window.location.reload();\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("        <SCRIPT>\r\n");
      out.write("            $(function() {\r\n");
      out.write("                $('.left .item').draggable({\r\n");
      out.write("                    revert: true,\r\n");
      out.write("                    proxy: 'clone'\r\n");
      out.write("                });\r\n");
      out.write("                $('.right td.drop').droppable({\r\n");
      out.write("                    accept: '.item',\r\n");
      out.write("                    onDragEnter: function() {\r\n");
      out.write("                        $(this).addClass('over');\r\n");
      out.write("                    },\r\n");
      out.write("                    onDragLeave: function() {\r\n");
      out.write("                        $(this).removeClass('over');\r\n");
      out.write("                    },\r\n");
      out.write("                    onDrop: function(e, source) {\r\n");
      out.write("                        $(this).removeClass('over');\r\n");
      out.write("                        if ($(source).hasClass('assigned')) {\r\n");
      out.write("                            $(this).append(source);\r\n");
      out.write("                        } else {\r\n");
      out.write("                            var c = $(source).clone().addClass('assigned');\r\n");
      out.write("                            $(this).empty().append(c);\r\n");
      out.write("                            c.draggable({\r\n");
      out.write("                                revert: true\r\n");
      out.write("                            });\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                $('.left').droppable({\r\n");
      out.write("                    accept: '.assigned',\r\n");
      out.write("                    onDragEnter: function(e, source) {\r\n");
      out.write("                        $(source).addClass('trash');\r\n");
      out.write("                    },\r\n");
      out.write("                    onDragLeave: function(e, source) {\r\n");
      out.write("                        $(source).removeClass('trash');\r\n");
      out.write("                    },\r\n");
      out.write("                    onDrop: function(e, source) {\r\n");
      out.write("                        $(source).remove();\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        </SCRIPT>\r\n");
      out.write("\r\n");
      out.write("        </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
